
  
  intl: ^0.20.2
  
  
    
  equatable: ^2.0.7
  
  sqflite: ^2.4.1
  path: ^1.9.0
  flutter_layout_grid: ^2.0.7
  sprung: ^3.0.1
  
  
  liquid_pull_to_refresh: ^3.0.1
  
  url_launcher: ^6.3.1
  event_bus: ^2.0.1
  flutter_compass: ^0.8.1
  vibration: ^3.1.2
  share_plus: ^10.1.4
  
  dashed_circular_progress_bar: ^0.0.6
  fl_chart: ^0.70.2
  synchronized: ^3.3.0+3




  