include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    constant_identifier_names: ignore
    empty_catches: ignore
    must_be_immutable: ignore
    non_constant_identifier_names: ignore
    use_build_context_synchronously: ignore
formatter:
  page_width: 120
  trailing_commas: preserve